### ISSUE TITLE
[suggestion] electrical motor

### ISSUE THREAD

**Issue by Biviho** [RCXcrafter/Mystical-Gears#12]
hi! i have a suggestion for your mod: an electrical motor.
I can't find a mod that add an electrical motor to convert rf to mechanical energy, and, looking that you have a mechanical dinamo, i tought it would fit in your mod

**Comment by RCXcrafter** [comment]
I have considered adding an rf motor but I decided not to do it because I think rf is too easy to get. I'm afraid players would just hook it up to their big reactor instead of trying the other ways you can generate mechanical power.

**Comment by Biviho** [comment]
i can see your point, but i have to say that it can depend on the modpack environment and on the config.
If you will ever reconsider to add it to the mod i suggest a rf-to-mp conversion rate (obviously) as well as (if possible) a way to make other sources more reliable: for example it could be a gear to put in the motor that will break from time to time,  or a limit on the lenght of axles connected before it breaks, things like that
