### ISSUE TITLE
Suggestion: Better Mechanical Dial output

### ISSUE THREAD

**Issue by Circine** [RCXcrafter/Mystical-Gears#5]
Putting it on moving axles is silly, could it be made to read all the faces of a connected gearbox, with an indicator for input and output? The One Probe does something like this but I'd like to require the dial be placed like other Embers machines instead of using TOP's probe.

**Comment by RCXcrafter** [comment]
I could allow it to read and display all sides but I'm not sure how I would indicate on which side each of the power values is. I could label them north, east, etc. but there's no proper/easy ingame way to see what north is in the world.

**Comment by Circine** [comment]
The directions aren't necessarily too important, since a gearbox has only one input and all outputs are always equal. Most if not all of the mechanical converters added by this mod and others only have a single input and output.
Only confusing one might be mergeboxes, since they can have different value inputs(although this will prevent them from being added properly). Even if you can't see which side is off, it'd still give the user enough info to see there's a problem and investigate it themselves.
