### ISSUE TITLE
[Crash] Mechanical Dial

### ISSUE THREAD

**Issue by faeldray** [RCXcrafter/Mystical-Gears#6]
This happened randomly in my world even though I had never placed a dial. And trying to load the world caused the crash to happen immediately again. This happens only with version 1.1.1, version 1.1.0 seems fine.

https://paste.dimdev.org/fipegodiyo.mccrash

**Comment by RCXcrafter** [comment]
I'm not able to reproduce this crash but I've just released version 1.1.2 which should fix it. I'll reopen this issue if it still crashes.

**Comment by faeldray** [comment]
I haven't experienced any more crashes since updating so I think it worked. Thanks!

**Comment by Akaruz64** [comment]
Hey, i just started to get this issue out of nowhere, i'm playing in a Server of my own with my friend, both with the same Modpack and it only happens to me, never placed a dial in the server, we just started it.

Thanks.

https://pastebin.com/nJBZTuUm

**Comment by RCXcrafter** [comment]
This is fixed in version 1.1.2 if you update it should stop happening.

**Comment by Akaruz64** [comment]
Oh, never realized there was an update, was sure i had the latest version, Sorry and thanks!
